version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container-name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges: true