version: '3'

services:
  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitor  
      - loki
    restart: unless-stopped
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks:
  monitor:
    external:
      name: monitor
  loki:
    external:
      name: loki    