version: '3'

services:
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    networks:
      - monitor  
    restart: unless-stopped
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks:
  monitor:
    external:
      name: monitor